services:

  postgres:
    image: postgres:16
    container_name: tcc_postgres
    restart: always

    environment:
      POSTGRES_DB: ${CUSTOMER_DATABASE}
      POSTGRES_USER: ${PRODUCT_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

    ports:
      - "5433:5432"

    volumes:
      - ./Database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data


  customerservice:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile

    container_name: customer_service

    ports:
      - "5001:8080"

    depends_on:
      - postgres

    environment:
      ConnectionStrings__DefaultConnection: Host=${DB_HOST};Port=${DB_PORT};Database=${CUSTOMER_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}


  productservice:
    build:
      context: ./ProductService
      dockerfile: Dockerfile

    container_name: product_service

    ports:
      - "5002:8080"

    depends_on:
      - postgres

    environment:
      ConnectionStrings__DefaultConnection: Host=${DB_HOST};Port=${DB_PORT};Database=${PRODUCT_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}